export const actionTypes = {
    FETCH_MEMBERS_COMPLETED: 'FETCH_MEMBERS_COMPLETED',
    FETCH_MEMBER_BY_ID_COMPLETED: 'FETCH_MEMBER_BY_ID_COMPLETED',
    UPDATE_MEMBER_FIELD: 'UPDATE_MEMBER_FIELD',
    SAVE_MEMBER: 'SAVE_MEMBER',
    FETCH_FILTERED_CARDS_COMPLETED: 'FETCH_FILTERED_CARDS_COMPLETED',
    FETCH_CARD_COMPLETED: 'FETCH_CARD_COMPLETED',
    UPDATE_CARD_SEARCH_FIELD: 'UPDATE_CARD_SEARCH_FIELD',
    FETCH_FILTERED_SETS_COMPLETED: 'FETCH_FILTERED_SETS_COMPLETED'
  };