export const actionTypes = {
    FETCH_FILTERED_CARDS_COMPLETED: 'FETCH_FILTERED_CARDS_COMPLETED',
    FETCH_CARD_COMPLETED: 'FETCH_CARD_COMPLETED',
    UPDATE_CARD_SEARCH_FIELD: 'UPDATE_CARD_SEARCH_FIELD',
    FETCH_FILTERED_SETS_COMPLETED: 'FETCH_FILTERED_SETS_COMPLETED',
    FETCH_CARD_SYMBOLS_COMPLETED: 'FETCH_CARD_SYMBOLS_COMPLETED'
  };